# fly.toml app configuration file generated for clegrand on 2024-04-29T19:20:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clegrand'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'
console_command = '/rails/bin/rails console'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'bin/rails db:prepare'

[env]
  PORT = '3000'
  RAILS_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
